### ISSUE TITLE
Non-descriptive errors/error loop for Incremental 5 - Forms

### ISSUE THREAD

**Issue by jcarrschwab** [Section508Coordinators/DHSA-TT-200-A#132] opened 2019-06-17 19:18 UTC
![FormsIncremental](https://user-images.githubusercontent.com/51755970/59630407-3a4c5d00-9113-11e9-8cc1-4c6218a78a16.PNG)
If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues.

## Issue Type (put an X between the brackets to indicate issue type)
- [ x] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
When completing incremental test for Forms, I left all fields blank. 
I clicked "Get Captcha" but left it blank. 
I clicked submit. 
I got a series of "Error" dialog boxes with no further information about the error, and sometimes was in a loop requiring a page refresh.

## Location
http://3.217.25.10/dhsv5/scormapi/lesson1.php?SCOInstanceID=195&studentName=Joyce%20CarrSchwab&ltiUserId=4413&studentEmail=joyce.carrschwab@associates.ice.dhs.gov&examId=5

**Comment by drewnielson** [comment] 2019-06-17 20:32
Well, this looks like a fun one. @jcarrschwab, would you mind trying again and let me know if you get the same result from the test page you linked above? I couldn't reproduce the issue, and I wonder if it had anything to do with the system-wide issue we experienced earlier. If so, then that issue has been resolved, and you shouldn't see this issue anymore. If you are still seeing the issue, then I'll need to investigate further.

**Comment by jcarrschwab** [comment] 2019-06-17 20:39
Retested - appears to be coincidental with the outage. I'd consider it closed.

**Comment by drewnielson** [comment] 2019-06-17 21:24
OK, thanks. Happy to close it :)

**Closed by drewnielson** 2019-06-17 21:24 UTC
Labels: exam-incremental, studentissue
