### ISSUE TITLE
Answers for 4.E and 4.F in Incremental Exam

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#206] opened 2019-07-02 11:32 UTC
## Issue Type (put an X between the brackets to indicate issue type)
- [x ] Incorrect content

## Description
Answer key appears to be wrong for incremental exam for Topic 4
1.	4.E – When an interface element receives focus, it does not initiate an unexpected change of context.
When the “time out” notification appears, use of the Tab key closes the box, rather than moving focus to the Continue button or the x on the message. Instructions do specify to select the button to continue. 
2.	4.F - The focus order preserves the meaning and operability of the Web page.
There are 3 instances where focus order does not preserve meaning and operability:
a)	Company phone is skipped after HR Email form field and before Company Address
b)	Selecting the Get Super-Certified checkbox does not expand details below it as is stated on the page.
c)	The City form field does not receive focus after the State form filed and is the beginning of a keyboard trap.
The answer sheet only shows 2 failures for this web page for 4.F. See answer key below.
 
## Location
[Topic 4, Incremental exam 
http://3.217.25.10/dhsv5/dhscourse/Lesson1/exams/web-incremental/testPages/page3_main.php?KeyID=840 ]

**Comment by drewnielson** [comment] 2019-07-03 19:33
@AnnMarieDavis, could  you edit your original comment to also include the url for the specific page you tested for this?

**Comment by Tonylayton1** [comment] 2019-07-08 18:10
To address 4.E, change the timeout message in the 10 second and 20 second popups to say "any key" instead of "continue". should say "Select any key to remain on this page and complete the form."

For the three 4.F issues:
a) It looks like 4.F should also include any fields that aren't keyboard accessible. To address this, r2_6 would need to be added to the list of 4.F failures, and 4.A would need to be added to the cluster of failures involving 4.F, as all of these would have to fail together.
b) this is the second time this has come up and I still cannot replicate it. The expanded section always opens for me.
c) the keyboard trap is already included on the 4.F fail list.

**Comment by mikebarklage** [comment] 2019-07-08 19:02
Updated the timeout message on incremental/practice/final exams to say "any key."

**Comment by drewnielson** [comment] 2019-07-08 19:08
Agree with language change in the timeout warning. That should make the interaction clearer.

Agreed with point in a), at least in this instance would make sense, given how the student is identifying the issues.

I also cannot replicate b). The section displays after selecting the Get Super-Certified checkbox. I'll investigate further on Ann Marie's machine.

**Comment by drewnielson** [comment] 2019-07-08 19:15
Disregard comment related to b) - content not displaying after selecting the Get Super-Certified checkbox. Unable to reproduce on Ann Marie's computer now too.

**Comment by mikebarklage** [comment] 2019-07-08 19:18
Just to check, the changes so far are:

1. Add r2_6 to the answers for 4.F

2. 4.A, 4.C, 4.F, 4.G, and 4.H should all be linked as NC or C together (adding 4.A to that list)

**Comment by Tonylayton1** [comment] 2019-07-08 19:33
Including the timeout text change, yes that should be it.

**Comment by mikebarklage** [comment] 2019-07-08 19:58
OK, these changes are done. Don't forget to clear data for topic 4 exams for testing.

**Comment by Tonylayton1** [comment] 2019-07-09 17:29
Verified on Dev

**Comment by AnnMarieDavis** [comment] 2019-07-09 21:03
I retested. For 4.F - The focus order preserves the meaning and operability of the Web page.
a)	Company phone is skipped after HR Email form field and before Company Address. All other answers ask students to choose the LAST item that received focus. The correct choice for that instance should be HR Email rather than Company Phone.
![Issue 206 for 4F](https://user-images.githubusercontent.com/31414225/60922747-f28da100-a28c-11e9-88be-208b56810049.png)

**Comment by Tonylayton1** [comment] 2019-07-09 21:52
this is addressed in issue #221 which specifies the reporting instructions - if everything else from this issue is resolved then this can be closed.

**Comment by AnnMarieDavis** [comment] 2019-07-10 13:36
The instructions are addressed in #221, however the issue here is that the wrong element is referenced in the answer key. Instead of "company phone", the answer should be "HR element"

**Comment by Tonylayton1** [comment] 2019-07-10 14:24
to clarify, yes I added what you have described to that issue, because multiple answers were affected by the updated instructions (4.F and 4.H)

**Comment by drewnielson** [comment] 2019-07-12 12:44
verified in dev

**Closed by drewnielson** 2019-07-12 12:44 UTC
Labels: exam-incremental
