### ISSUE TITLE
15.B- incorrect answer in Practice Exam?

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#149] opened 2019-06-18 16:27 UTC
SCO ID: 109, Web Practice | submitted 2019-06-18 16:17:02 | Page 1 \| Page 2 \| Page 3

_Page 3_ results say 15.B should be NC, but when I linearize the frame, no content shows. B/c no content shows, I mark DNA. Except! results say it should be NC. Web page: http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/page3_main.php?KeyID=1306 
![image](https://user-images.githubusercontent.com/34742733/59701355-75a66480-91c3-11e9-939a-a031f36eda9d.png)

At any rate, the image below shows that the content they say should fail definitely does not linearize:

![image](https://user-images.githubusercontent.com/34742733/59701802-5d831500-91c4-11e9-81f7-a36dc03b573b.png)

**Comment by Tonylayton1** [comment] 2019-07-23 23:25
Update the webpage so that the 2 lists are side by side even when 15.B fails
When 15.B fails, the lists should be organized visually with CSS to look the same as the passing version, but they are actually stacked on the webpage as: Header 1, Header 2, List 1, List 2

**Comment by mikebarklage** [comment] 2019-07-24 18:58
This had been keying off of 13.B - the two IDs used to be linked. Changed it to 15.B.

**Comment by Tonylayton1** [comment] 2019-07-25 22:19
I am still seeing the same orientation as before. When 15.B fails, the lists are visually one on top of the other instead of side-by-side. 

A screen reader would correctly identify the failure (would read the two headers first and then the two lists) but ANDI is not identifying it with the "linearize page" function.

That said, the desired result would be that the two lists appear side-by-side, but when 'linearize page' is selected it shows as header header list list from top to bottom.

**Comment by mikebarklage** [comment] 2019-07-25 22:47
So... is it an issue with ANDI's linearize functionality?

**Comment by Tonylayton1** [comment] 2019-07-25 22:49
It could be. the first part of the issue is getting it to look visually like the compliant version. could we try that and see what ANDI does?

**Comment by mikebarklage** [comment] 2019-07-25 23:55
Ah, I got confused on that part. Should be fixed now. I still don't see ANDI doing anything with it, though.

**Comment by Tonylayton1** [comment] 2019-07-26 20:45
Okay I can confirm they look identical now. 

The issue is that even though they are definitely only in the correct order visually because of CSS, linearize page does not show the issue. If you highlight the list headers and lists with a mouse or disable CSS you can see that the reading order would be wrong. Not sure what to do here.

Here is the order when CSS is disabled:

![image](https://user-images.githubusercontent.com/52048615/61980443-cc723b80-afc4-11e9-93d6-1c011bd90aff.png)

**Comment by drewnielson** [comment] 2019-07-31 17:15
I sent the issue to the ANDI developer at SSA. In the meantime let's add position:relative to each of the styles so ANDI will at least highlight those sections.

So in the style added to the `<head>` element: 
```<style>
		.header {
                        position: relative;
			float: left;
			width: 50%;
			text-align: center;
			margin-bottom: 15px;
		}
		
		.thumb-print, .retinal-scan {
                        position: relative;
			float: left;
			width: 50%;
		}
```

**Comment by mikebarklage** [comment] 2019-07-31 17:35
Done.

**Comment by drewnielson** [comment] 2019-07-31 18:06
verified on dev

**Closed by drewnielson** 2019-07-31 18:06 UTC
Labels: CarneyFix, exam-practice
